---
apiVersion: v1
kind: Pod
metadata:
  name: limits
spec:
  containers:
    - name: podslimits
      image: httpd
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
        requests:
          memory: "64Mi"
          cpu: "100m"